import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from 'ynn/styles/Home.module.css'
import Banner from '../components/banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(`styles`,styles);
  return (
    <>
      <Head>
        <title>Create </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <Banner/>

        
      
    </>
  )
}
